# Generated by Django 5.0.2 on 2025-05-18 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_cementerio', '0002_superuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SuperUser',
        ),
    ]
