# Generated by Django 5.0.2 on 2025-05-30 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_cementerio', '0003_delete_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dceasced',
            name='date_of_born',
        ),
    ]
