# Generated by Django 5.0.2 on 2025-05-31 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_cementerio', '0004_remove_dceasced_date_of_born'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grave',
            name='num',
            field=models.IntegerField(unique=True),
        ),
    ]
